### ISSUE TITLE
Publish library ReclaimerLabs_Thermocouple

### ISSUE THREAD

**Issue by monkbroc** [ReclaimerLabs/ReclaimerLabs_ADS1118#2]
When compiling the example I got `Library ReclaimerLabs_Thermocouple not found`. Could you make sure to publish the ReclaimerLabs_Thermocouple library?

**Comment by ReclaimerLabs** [comment]
Everything should be published. I have at least one other person successfully using both libraries for their project. I've noticed some inconsistencies with the Particle IDE in general. I just went to try to compile the library, and it initially complained about not having ReclaimerLabs_ADS1118.h. Then I restarted my browser, and it compiles now. Not sure what's going on here...

**Comment by monkbroc** [comment]
My bad, my CLI was still on the staging server when I ran the check against your library. Everything's good!
